In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
## Define vocabulary size
voc_size=10000

In [15]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1293, 8863, 2506, 3534],
 [1293, 8863, 2506, 3904],
 [1293, 6148, 2506, 737],
 [7482, 4753, 7223, 3383, 1958],
 [7482, 4753, 7223, 3383, 3877],
 [5815, 1293, 9441, 2506, 8412],
 [1814, 2037, 5657, 3383]]

In [16]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1293 8863 2506 3534]
 [   0    0    0    0 1293 8863 2506 3904]
 [   0    0    0    0 1293 6148 2506  737]
 [   0    0    0 7482 4753 7223 3383 1958]
 [   0    0    0 7482 4753 7223 3383 3877]
 [   0    0    0 5815 1293 9441 2506 8412]
 [   0    0    0    0 1814 2037 5657 3383]]


In [18]:
## Feature Representation
dim=10  #Dimension

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\Deep Learning\Simple RNN(Movie Review)\venv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step


array([[[-4.2985570e-02, -2.5785342e-03, -2.4830587e-03, -2.3544360e-02,
         -4.5534875e-02,  4.7217373e-02,  2.5183726e-02, -4.6690226e-02,
          8.2337856e-04, -3.5005294e-02],
        [-4.2985570e-02, -2.5785342e-03, -2.4830587e-03, -2.3544360e-02,
         -4.5534875e-02,  4.7217373e-02,  2.5183726e-02, -4.6690226e-02,
          8.2337856e-04, -3.5005294e-02],
        [-4.2985570e-02, -2.5785342e-03, -2.4830587e-03, -2.3544360e-02,
         -4.5534875e-02,  4.7217373e-02,  2.5183726e-02, -4.6690226e-02,
          8.2337856e-04, -3.5005294e-02],
        [-4.2985570e-02, -2.5785342e-03, -2.4830587e-03, -2.3544360e-02,
         -4.5534875e-02,  4.7217373e-02,  2.5183726e-02, -4.6690226e-02,
          8.2337856e-04, -3.5005294e-02],
        [ 3.2077346e-02,  1.1902429e-02, -2.0585656e-02,  4.4161689e-02,
          4.8955869e-02, -6.3155405e-03, -1.6725123e-02, -3.1825982e-02,
         -6.8617687e-03,  8.3624013e-03],
        [-3.3158828e-02, -3.9169289e-02, -1.9763995e-02, -3.

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 1293, 8863, 2506, 3534])

In [27]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None